### ISSUE TITLE
Google OAuth 2.0 not integrated with MongoDB

### ISSUE THREAD

**Issue by muhdhasan** [TanukiHQ/Genkan#16]

**Comment by Dylankjy** [comment]
#6 has significant changes in the session schema and user schema. Be sure you make sure you have the correct setup before proceeding.

**MongoDB Collections**
- users
- sessions

Delete all old users before attempting an integration.

**Comment by muhdhasan** [comment]
Alright. Will take note of the changes.

**Comment by muhdhasan** [comment]
Most of the oAuth is working as it should as of now. Probably gonna merge it tomorrow after some more testing.
